assignment1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('yourlist/', include('yourlist.urls')),
    path('admin/', admin.site.urls),
    path('', include('django_prometheus.urls')),
]

yourlist/urls.py
from django.urls import path
from . import views

app_name = 'yourlist'
urlpatterns = [
    path('', views.index, name='index'),
    path('user/<int:person_id>/', views.userView, name='userView'),
    path('user/create/', views.userCreate, name='userCreate'),
    path('user/<int:person_id>/delete/', views.userDelete, name='userDelete'),
    path('user/<int:person_id>/newinterest/', views.interestCreate, name='interestCreate'),
    path('user/interest/<int:interest_id>/delete/', views.interestRemove, name='interestRemove')
]

yourlist/models.py
from django.db import models

CATEGORY_OPTIONS = (('sport','Sport'), ('politics','Politics'), ('music','Music'), ('technology','Technology'),('miscellanues','Miscellanues'),)

class Person(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    age = models.IntegerField(default=0)

    def __str__(self):
        return self.surname

class Interest(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    category = models.CharField(max_length=255, choices=CATEGORY_OPTIONS)

    def __str__(self):
        return self.description

# Create your models here.

yourlist/forms.py
from django import forms
from .models import Person, Interest

class UserForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ["name", "surname", "age"]

class InterestForm(forms.ModelForm):
    class Meta:
        model = Interest
        fields = ["person","description", "category"]

yourlist/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect

from .forms import UserForm, InterestForm
# from django.http import HttpResponse

from .models import Person, Interest
from django.views import generic
from .forms import UserForm

def index(request):
    users_list = Person.objects.all()
    context = {
        'users_list': users_list,
    }
    return render(request, 'yourlist/index.html', context)

def userView(request, person_id):
    try:
        user = Person.objects.get(pk=person_id)
        interests_list = Interest.objects.filter(person_id=person_id)
        context = {
            'interests_list': interests_list,
            'user': user,
        }
    except Person.DoesNotExist:
        raise Http404("Ops! It seems the person you are looking for does not exist in our system")
    return render(request, 'yourlist/userview.html', context)

def userCreate(request):
    form = UserForm(request.POST or None)

    form_valid = form.is_valid()

    if form_valid:
        form.save()

    context = {
        'form': form,
        'form_valid': form_valid
    }
    
    return render(request, 'yourlist/usercreate.html', context)

def userDelete(request, person_id):
    user = Person.objects.filter(pk=person_id)
    user.delete()

    context = {
        'user': user,
    }

    return render(request, 'yourlist/userdelete.html', context)

def interestCreate(request, person_id):

    user = Person.objects.get(pk=person_id)

    form = InterestForm(request.POST or None, initial={'person': person_id})

    form_valid = form.is_valid()

    if form_valid:
        form.save()
    
    context = {
        'user': user,
        'form': form,
        'form_valid': form_valid
    }

    return render(request, 'yourlist/interestcreate.html', context)

def interestRemove(request, interest_id):
    interest = Interest.objects.get(pk=interest_id)
    user = Person.objects.get(pk=interest.person_id)
    interest.delete()

    context = {
        'user': user,
        'interest': interest,
        'user': user,
    }

    return render(request, 'yourlist/interestremove.html', context)

# Create your views here.

yourlist/templates/yourlist/base.html
<!-- This file defines the base structure that every html file in templates
    must have -->

{% load bootstrap4 %}
{% load static %}

{% bootstrap_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">YourList WebApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://192.168.99.100:3000" target="_blank">Grafana</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://192.168.99.100:9090" target="_blank">Prometheus</a>
            </li>
            </ul>
        </div>
    </nav>
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>

<!-- Test comment for oral exam -->

yourlist/templates/yourlist/index.html
{% extends 'yourlist/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <section>
        {% if users_list %}
            <ul>
            {% for user in users_list %}
                <li><a href="{% url 'yourlist:userView' user.id %}">{{ user.name }} {{ user.surname }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p><i>No users have been signed up yet</i></p>
        {% endif %}

        <form action="{% url 'yourlist:userCreate' %}">
            {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Create new user
                </button>
            {% endbuttons %}
        </form>
    </section>
{% endblock %}

yourlist/templates/yourlist/interestcreate.html
{% extends 'yourlist/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <section>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Create!
                </button>
            {% endbuttons %}
        </form>

        {% if form_valid %}
            <p>Interest successfully added!</p>
        {% endif %}
        <form action="{% url 'yourlist:userView' user.id %}">
                {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Go back
                </button>
            {% endbuttons %}
        </form>
    </section>
{% endblock %}

yourlist/templates/yourlist/interestremove.html
{% extends 'yourlist/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <section>
        <p>Interest {{ interest.description }} for user {{ user.name }} {{ user.surname }} has been deleted from database!</p>

        <form action="{% url 'yourlist:userView' user.id %}">
            {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Go back
                </button>
            {% endbuttons %}
        </form>
    </section>
{% endblock %}

yourlist/templates/yourlist/usercreate.html
{% extends 'yourlist/base.html' %}
{% load bootstrap4 %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% block content %}
    <section>
        <div class="form-wrapper">
            <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Create
                </button>
            {% endbuttons %}
            </form>   
        </div>
            
        {% if form_valid %}
            <p>User successfully created!</p>
        {% endif %}
        <form action="{% url 'yourlist:index' %}">
            {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Go back home
                </button>
            {% endbuttons %}
        </form>
    </section>
{% endblock %}

yourlist/templates/yourlist/userdelete.html
{% extends 'yourlist/base.html' %}
{% load bootstrap4 %}

{% block content %}
    <section>
        <p>User {{ user.name }} {{ user.surname }} has been deleted from database!</p>

        <form action="{% url 'yourlist:index' %}">
                {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Go back home
                </button>
            {% endbuttons %}
        </form>
    </section>
{% endblock %}

yourlist/templates/yourlist/userview.html
{% extends 'yourlist/base.html' %}
{% load bootstrap4 %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% block content %}
    <section>
        <h2>{{ user.name }} {{ user.surname }}'s profile | {{ user.age }} anni</h2>
        <hr/>
        <form action="{% url 'yourlist:userDelete' user.id %}">
            {% buttons %}
                <button type="submit" class="btn btn-dark inline">
                  Delete this user
                </button>
            {% endbuttons %}
        </form>
        <form action="{% url 'yourlist:interestCreate' user.id %}">
            {% buttons %}
                <button type="submit" class="btn btn-dark inline">
                  Add new interest
                </button>
            {% endbuttons %}
        </form>
        <hr/>
        <p>Here you can see {{ user.name }} {{ user.surname }}'s' interests. You can ADD a new interest by clicking on button above or REMOVE an old one by clicking on it.
        </p>
        <p>You can also REMOVE this user from our database, clicking the button above.</p>

        {% if interests_list %}
        <ul>
            {% for interest in interests_list %}
                <li><a href="{% url 'yourlist:interestRemove' interest.id %}">{{ interest.description }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p><i>No interest has been assigned to this user</i></p>
        {% endif %}

        <form action="{% url 'yourlist:index' %}">
                {% buttons %}
                <button type="submit" class="btn btn-dark">
                  Go back home
                </button>
            {% endbuttons %}
        </form>
    </section>
{% endblock %}